---

- name: start firewalld service
  become: true
  service:
    name: firewalld
    state: started

- name: start httpd service
  become: true
  service:
    name: httpd
    state: started

- name: add HTTP service
  become: true
  command: firewall-cmd --permanent --zone=public --add-service=http

- name: restart firewalld
  become: true
  service:
    name: firewalld
    state: restarted

- name: add HTTPS service
  become: true
  command: firewall-cmd --permanent --zone=public --add-service=https

- name: selinux configuration
  become: true
  command: restorecon -FR /var/www/html/mediawiki
  notify: service restart

