---

- name: start firewalld service
  become: true
  service:
    name: firewalld
    state: started

- name: start httpd service
  become: true
  service:
    name: httpd
    state: started

- name: add HTTP service
  become: true
  firewalld:
    service: http
    permanent: true
    zone: public
    state: enabled

- name: add http service
  become: true
  command: sh /tmp/mediaWiki_terraform_ansible_AWS/media_wiki_ansible/firewalld.sh

- name: add HTTPS service
  become: true
  firewalld:
    service: https
    permanent: true
    zone: public
    state: enabled

- name: selinux configuration
  become: true
  shell: restorecon -FR /var/www/html/mediawiki

- name: restart firewalld
  become: true
  service:
    name: firewalld
    state: restarted
